package com.myclass.gui;

import com.myclass.bus.KhachSanBUS;
import com.myclass.dao.KhachSanDAO;
import com.myclass.dto.KhachSanDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Thin
 */
public class KhachSanGUI extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    List<KhachSanDTO> khachsanList = new ArrayList<>();

    /**
     * Creates new form KhachSan
     */
    public KhachSanGUI() {
        initComponents();
        tableModel = (DefaultTableModel) tblKhachSan.getModel();      
    }

    private void showKhachSan() {
        khachsanList = KhachSanBUS.xemDSKS();
        tableModel.setRowCount(0);

        khachsanList.forEach(ksDTO -> {
            tableModel.addRow(new Object[]{
                ksDTO.getMaKS(), ksDTO.getTenKS(), ksDTO.getDiachiKS(), ksDTO.getWebsite(), ksDTO.getSoDT(), ksDTO.getChiphi()

            });
        });
    }
    
    private void showData(){
        int selectedIndex = tblKhachSan.getSelectedRow();
        if (selectedIndex >= 0) {
            KhachSanDTO ksDTO = khachsanList.get(selectedIndex);
            
            txtMaKhachSan.setText(ksDTO.getMaKS());
            txtTenKhachSan.setText(ksDTO.getTenKS());
            txtDiaChi.setText(ksDTO.getDiachiKS());
            txtWebsite.setText(ksDTO.getWebsite());
            txtSoDienThoai.setText(ksDTO.getSoDT());
            txtChiPhi.setText(Integer.toString(ksDTO.getChiphi()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        lbDanhMucKhachSan = new javax.swing.JLabel();
        lbLogoKhachSan = new javax.swing.JLabel();
        lbMaKhachsan = new javax.swing.JLabel();
        lbTenKhachSan = new javax.swing.JLabel();
        txtTenKhachSan = new javax.swing.JTextField();
        lbDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lbChiPhi = new javax.swing.JLabel();
        txtChiPhi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachSan = new javax.swing.JTable();
        btnTimKiemKhachSan = new javax.swing.JButton();
        btnXoaThongTinKhachSan = new javax.swing.JButton();
        lbWebsite = new javax.swing.JLabel();
        txtWebsite = new javax.swing.JTextField();
        lbSoDienThoai = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        btnLuuThongTinKhachSan = new javax.swing.JButton();
        btnSuaThongTinKhachSan = new javax.swing.JButton();
        btnXemDanhSachKhachSan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        txtMaKhachSan = new javax.swing.JTextField();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        lbDanhMucKhachSan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbDanhMucKhachSan.setForeground(new java.awt.Color(153, 0, 0));
        lbDanhMucKhachSan.setText("DANH Má»¤C KHÃ�CH Sáº N");

        lbLogoKhachSan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Thin\\OneDrive\\MÃ¡y tÃ­nh\\java\\QuanLyTourDuLich\\src\\main\\java\\IMAGE\\logoKhachSan.PNG")); // NOI18N
        lbLogoKhachSan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbMaKhachsan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbMaKhachsan.setForeground(new java.awt.Color(0, 0, 0));
        lbMaKhachsan.setText("MÃ£ khÃ¡ch sáº¡n");

        lbTenKhachSan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbTenKhachSan.setForeground(new java.awt.Color(0, 0, 0));
        lbTenKhachSan.setText("TÃªn khÃ¡ch sáº¡n");

        lbDiaChi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbDiaChi.setForeground(new java.awt.Color(0, 0, 0));
        lbDiaChi.setText("Ä�á»‹a chá»‰");

        lbChiPhi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbChiPhi.setForeground(new java.awt.Color(0, 0, 0));
        lbChiPhi.setText("Chi phÃ­ / PhÃ²ng");

        tblKhachSan.setBackground(new java.awt.Color(204, 204, 255));
        tblKhachSan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        tblKhachSan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tblKhachSan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ£ khÃ¡ch sáº¡n", "TÃªn khÃ¡ch sáº¡n", "Ä�á»‹a chá»‰", "Website", "Sá»‘ Ä‘iá»‡n thoáº¡i", "Chi phÃ­/ PhÃ²ng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachSan.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblKhachSan);

        btnTimKiemKhachSan.setBackground(new java.awt.Color(204, 204, 255));
        btnTimKiemKhachSan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTimKiemKhachSan.setForeground(new java.awt.Color(0, 0, 0));
        btnTimKiemKhachSan.setText("TÃ¬m Kiáº¿m KhÃ¡ch Sáº¡n");
        btnTimKiemKhachSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemKhachSanActionPerformed(evt);
            }
        });

        btnXoaThongTinKhachSan.setBackground(new java.awt.Color(204, 204, 255));
        btnXoaThongTinKhachSan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoaThongTinKhachSan.setForeground(new java.awt.Color(0, 0, 0));
        btnXoaThongTinKhachSan.setText("XÃ³a ThÃ´ng Tin KhÃ¡ch Sáº¡n");
        btnXoaThongTinKhachSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaThongTinKhachSanActionPerformed(evt);
            }
        });

        lbWebsite.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbWebsite.setForeground(new java.awt.Color(0, 0, 0));
        lbWebsite.setText("WebSite");

        lbSoDienThoai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbSoDienThoai.setForeground(new java.awt.Color(0, 0, 0));
        lbSoDienThoai.setText("Sá»‘ Ä‘iá»‡n thoáº¡i");

        btnLuuThongTinKhachSan.setBackground(new java.awt.Color(204, 204, 255));
        btnLuuThongTinKhachSan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLuuThongTinKhachSan.setForeground(new java.awt.Color(0, 0, 0));
        btnLuuThongTinKhachSan.setText("LÆ°u ThÃ´ng Tin KhÃ¡ch Sáº¡n");
        btnLuuThongTinKhachSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuThongTinKhachSanActionPerformed(evt);
            }
        });

        btnSuaThongTinKhachSan.setBackground(new java.awt.Color(204, 204, 255));
        btnSuaThongTinKhachSan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSuaThongTinKhachSan.setForeground(new java.awt.Color(0, 0, 0));
        btnSuaThongTinKhachSan.setText("Sá»­a ThÃ´ng Tin KhÃ¡ch Sáº¡n");
        btnSuaThongTinKhachSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaThongTinKhachSanActionPerformed(evt);
            }
        });

        btnXemDanhSachKhachSan.setBackground(new java.awt.Color(204, 204, 255));
        btnXemDanhSachKhachSan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXemDanhSachKhachSan.setForeground(new java.awt.Color(0, 0, 0));
        btnXemDanhSachKhachSan.setText("Xem danh sÃ¡ch khÃ¡ch sáº¡n");
        btnXemDanhSachKhachSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemDanhSachKhachSanActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(204, 204, 204));
        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(0, 0, 0));
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(204, 204, 204));
        btnCapNhat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(0, 0, 0));
        btnCapNhat.setText("Cáº¬P NHáº¬T");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTimKiemKhachSan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoaThongTinKhachSan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(btnLuuThongTinKhachSan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSuaThongTinKhachSan))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnXemDanhSachKhachSan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbLogoKhachSan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbMaKhachsan)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbWebsite)
                                                .addGap(191, 191, 191))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbDiaChi)
                                                    .addComponent(lbTenKhachSan))
                                                .addGap(227, 227, 227)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbSoDienThoai)
                                                    .addComponent(lbChiPhi))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(147, 147, 147)
                                        .addComponent(lbDanhMucKhachSan)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtTenKhachSan, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaKhachSan, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtChiPhi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtWebsite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbDanhMucKhachSan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbWebsite, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbMaKhachsan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaKhachSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTenKhachSan, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSoDienThoai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenKhachSan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDiaChi)
                            .addComponent(lbChiPhi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbLogoKhachSan)
                        .addGap(17, 17, 17)
                        .addComponent(btnXemDanhSachKhachSan)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiemKhachSan)
                    .addComponent(btnXoaThongTinKhachSan)
                    .addComponent(btnLuuThongTinKhachSan)
                    .addComponent(btnSuaThongTinKhachSan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnCapNhat))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemDanhSachKhachSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemDanhSachKhachSanActionPerformed
        // TODO add your handling code here:
        //khachsanList = KhachSanDAO.xemDSKS();
        showKhachSan();

    }//GEN-LAST:event_btnXemDanhSachKhachSanActionPerformed

    private void btnXoaThongTinKhachSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaThongTinKhachSanActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblKhachSan.getSelectedRow();
        if (selectedIndex >= 0) {
            KhachSanDTO ksDTO = khachsanList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Báº¡n cháº¯c cháº¯n xÃ³a thÃ´ng tin khÃ¡ch sáº¡n nÃ y ?");
            //System.out.println("option: " + option);
            //yes->0
            //No->1
            //Cancel->2
            if (option == 0) {
                KhachSanBUS.XoaTTKS(ksDTO.getMaKS());
                showKhachSan();
            }
        }
    }//GEN-LAST:event_btnXoaThongTinKhachSanActionPerformed

    private void btnLuuThongTinKhachSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuThongTinKhachSanActionPerformed
        // TODO add your handling code here:
        String maKS = txtMaKhachSan.getText();
        String tenKS = txtTenKhachSan.getText();
        String diachi = txtDiaChi.getText();
        String website = txtWebsite.getText();
        String soDT = txtSoDienThoai.getText();
        int chiphi = Integer.parseInt(txtChiPhi.getText());

        KhachSanDTO ksDTO = new KhachSanDTO(maKS, tenKS, diachi, website, soDT, chiphi);
        KhachSanBUS.LuuTTKS(ksDTO);
        showKhachSan();
    }//GEN-LAST:event_btnLuuThongTinKhachSanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtMaKhachSan.setText("");
        txtTenKhachSan.setText("");
        txtDiaChi.setText("");
        txtWebsite.setText("");
        txtSoDienThoai.setText("");
        txtChiPhi.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTimKiemKhachSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemKhachSanActionPerformed
        // TODO add your handling code here:
        Object[] options = {
            "TÃ¬m kiáº¿m theo mÃ£ khÃ¡ch sáº¡n", "TÃ¬m kiáº¿m theo tÃªn khÃ¡ch sáº¡n", "Ä�Ã³ng"
        };
        int select = JOptionPane.showOptionDialog(this, "Báº¡n muá»‘n tÃ¬m kiáº¿m theo phÆ°Æ¡ng thá»©c nÃ o ?", "TÃ¹y chá»�n", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[2]);
        //System.out.println("select: " + select);
        //mÃ£ -> select: 0
        //tÃªn -> select: 1
        // chi phi -> select: 2
        // Ä‘Ã³ng -> select: 3
        if (select == 0) {
            String input = JOptionPane.showInputDialog(this, "Má»�i nháº­p mÃ£ khÃ¡ch sáº¡n !");

            if (input != null && input.length() > 0) {
                khachsanList = KhachSanBUS.findByMaKS(input);

                tableModel.setRowCount(0);

                khachsanList.forEach(ksDTO -> {
                    tableModel.addRow(new Object[]{
                        ksDTO.getMaKS(), ksDTO.getTenKS(), ksDTO.getDiachiKS(), ksDTO.getWebsite(), ksDTO.getSoDT(), ksDTO.getChiphi()

                    });
                });
            } else {
                JOptionPane.showMessageDialog(null, "Lá»—i tÃ¬m kiáº¿m !");
            }

        }
        
        if(select == 1){
            String input = JOptionPane.showInputDialog(this,"Má»�i nháº­p tÃªn khÃ¡ch sáº¡n !");
            
            if (input != null && input.length() > 0) {
                khachsanList = KhachSanBUS.findByTenKS(input);

                tableModel.setRowCount(0);

                khachsanList.forEach(ksDTO -> {
                    tableModel.addRow(new Object[]{
                        ksDTO.getMaKS(), ksDTO.getTenKS(), ksDTO.getDiachiKS(), ksDTO.getWebsite(), ksDTO.getSoDT(), ksDTO.getChiphi()

                    });
                });
            } else {
                JOptionPane.showMessageDialog(null, "Lá»—i tÃ¬m kiáº¿m !");
            }
        }
    }//GEN-LAST:event_btnTimKiemKhachSanActionPerformed

    private void btnSuaThongTinKhachSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaThongTinKhachSanActionPerformed
        // TODO add your handling code here:
       showData();
    }//GEN-LAST:event_btnSuaThongTinKhachSanActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
         //TODO add your handling code here:
        String maKS = txtMaKhachSan.getText();
        String tenKS = txtTenKhachSan.getText();
        String diachi = txtDiaChi.getText();
        String website = txtWebsite.getText();
        String soDT = txtSoDienThoai.getText();
        int chiphi = Integer.parseInt(txtChiPhi.getText());

        KhachSanDTO ksDTO = new KhachSanDTO(maKS, tenKS, diachi, website, soDT, chiphi);
        
        KhachSanBUS.CapNhatTTKS(ksDTO);
        //showKhachSan();
        
        int i = tblKhachSan.getSelectedRow();
        KhachSanBUS.xemDSKS();
        tableModel.setValueAt(maKS, i, 0);
        tableModel.setValueAt(tenKS, i, 1);
        tableModel.setValueAt(diachi, i, 2);
        tableModel.setValueAt(website, i, 3);
        tableModel.setValueAt(soDT, i, 4);
        tableModel.setValueAt(chiphi, i, 5);
        tblKhachSan.setModel(tableModel);
    }//GEN-LAST:event_btnCapNhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachSanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachSanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachSanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachSanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachSanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuuThongTinKhachSan;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSuaThongTinKhachSan;
    private javax.swing.JButton btnTimKiemKhachSan;
    private javax.swing.JButton btnXemDanhSachKhachSan;
    private javax.swing.JButton btnXoaThongTinKhachSan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbChiPhi;
    private javax.swing.JLabel lbDanhMucKhachSan;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbLogoKhachSan;
    private javax.swing.JLabel lbMaKhachsan;
    private javax.swing.JLabel lbSoDienThoai;
    private javax.swing.JLabel lbTenKhachSan;
    private javax.swing.JLabel lbWebsite;
    private javax.swing.JTable tblKhachSan;
    private javax.swing.JTextField txtChiPhi;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaKhachSan;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenKhachSan;
    private javax.swing.JTextField txtWebsite;
    // End of variables declaration//GEN-END:variables
}
