package com.myclass.gui;

import com.myclass.bus.NhaHangBUS;
import com.myclass.dto.NhaHangDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Thin
 */
public class NhaHangGUI extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    List<NhaHangDTO> nhahangList = new ArrayList<>();
    /**
     * Creates new form NhaHang
     */
    public NhaHangGUI() {
        initComponents();
        tableModel = (DefaultTableModel) tblNhaHang.getModel();
    }
    
    private void showNhaHang(){
        nhahangList = NhaHangBUS.xemDSNH();
        
        tableModel.setRowCount(0);
        
        nhahangList.forEach(nhDTO -> {
            tableModel.addRow(new Object[]{
                nhDTO.getMaNH(), nhDTO.getTenNH(), nhDTO.getDiachi(), nhDTO.getWebsite(), nhDTO.getSoDT(), nhDTO.getChiphi()
            });
        });
    }
    
    private void showData(){
        int selectedIndex = tblNhaHang.getSelectedRow();
        
        if(selectedIndex >= 0){
            NhaHangDTO nhDTO = nhahangList.get(selectedIndex);
            
            txtMaNhaHang.setText(nhDTO.getMaNH());
            txtTenNhaHang.setText(nhDTO.getTenNH());
            txtDiaChi.setText(nhDTO.getDiachi());
            txtWebsite.setText(nhDTO.getWebsite());
            txtSoDienThoai.setText(nhDTO.getSoDT());
            txtChiPhi.setText(Integer.toString(nhDTO.getChiphi()));
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbDanhMucNhaHang = new javax.swing.JLabel();
        lbLogoNhaHang = new javax.swing.JLabel();
        lbMaNhaHang = new javax.swing.JLabel();
        txtMaNhaHang = new javax.swing.JTextField();
        lbTenNhaHang = new javax.swing.JLabel();
        txtTenNhaHang = new javax.swing.JTextField();
        lbDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lbChiPhi = new javax.swing.JLabel();
        txtChiPhi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhaHang = new javax.swing.JTable();
        btnTimKiemNhaHang = new javax.swing.JButton();
        btnXoaThongTinNhaHang = new javax.swing.JButton();
        lbWebsite = new javax.swing.JLabel();
        txtWebsite = new javax.swing.JTextField();
        lbSoDienThoai = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        btnLuuThongTinNhaHang = new javax.swing.JButton();
        tnSuaThongTinNhaHang = new javax.swing.JButton();
        btnXemDanhSachNhaHang = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        lbDanhMucNhaHang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbDanhMucNhaHang.setForeground(new java.awt.Color(153, 0, 0));
        lbDanhMucNhaHang.setText("DANH Má»¤C NHÃ€ HÃ€NG");

        lbLogoNhaHang.setIcon(new javax.swing.ImageIcon("C:\\Users\\Thin\\OneDrive\\MÃ¡y tÃ­nh\\java\\QuanLyTourDuLich\\src\\main\\java\\IMAGE\\logoNhaHang.PNG")); // NOI18N
        lbLogoNhaHang.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbMaNhaHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbMaNhaHang.setForeground(new java.awt.Color(0, 0, 0));
        lbMaNhaHang.setText("MÃ£ nhÃ  hÃ ng");

        lbTenNhaHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbTenNhaHang.setForeground(new java.awt.Color(0, 0, 0));
        lbTenNhaHang.setText("TÃªn nhÃ  hÃ ng");

        lbDiaChi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbDiaChi.setForeground(new java.awt.Color(0, 0, 0));
        lbDiaChi.setText("Ä�á»‹a chá»‰");

        lbChiPhi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbChiPhi.setForeground(new java.awt.Color(0, 0, 0));
        lbChiPhi.setText("Chi phÃ­ / NgÆ°á»�i");

        tblNhaHang.setBackground(new java.awt.Color(204, 204, 255));
        tblNhaHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        tblNhaHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tblNhaHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ£ nhÃ  hÃ ng", "TÃªn nhÃ  hÃ ng", "Ä�á»‹a chá»‰", "Website", "Sá»‘ Ä‘iá»‡n thoáº¡i", "Chi phÃ­/ NgÆ°á»�i"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNhaHang);

        btnTimKiemNhaHang.setBackground(new java.awt.Color(204, 204, 255));
        btnTimKiemNhaHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTimKiemNhaHang.setForeground(new java.awt.Color(0, 0, 0));
        btnTimKiemNhaHang.setText("TÃ¬m Kiáº¿m NhÃ  HÃ ng");
        btnTimKiemNhaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemNhaHangActionPerformed(evt);
            }
        });

        btnXoaThongTinNhaHang.setBackground(new java.awt.Color(204, 204, 255));
        btnXoaThongTinNhaHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoaThongTinNhaHang.setForeground(new java.awt.Color(0, 0, 0));
        btnXoaThongTinNhaHang.setText("XÃ³a ThÃ´ng Tin NhÃ  HÃ ng");
        btnXoaThongTinNhaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaThongTinNhaHangActionPerformed(evt);
            }
        });

        lbWebsite.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbWebsite.setForeground(new java.awt.Color(0, 0, 0));
        lbWebsite.setText("WebSite");

        lbSoDienThoai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbSoDienThoai.setForeground(new java.awt.Color(0, 0, 0));
        lbSoDienThoai.setText("Sá»‘ Ä‘iá»‡n thoáº¡i");

        btnLuuThongTinNhaHang.setBackground(new java.awt.Color(204, 204, 255));
        btnLuuThongTinNhaHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLuuThongTinNhaHang.setForeground(new java.awt.Color(0, 0, 0));
        btnLuuThongTinNhaHang.setText("LÆ°u ThÃ´ng Tin NhÃ  HÃ ng");
        btnLuuThongTinNhaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuThongTinNhaHangActionPerformed(evt);
            }
        });

        tnSuaThongTinNhaHang.setBackground(new java.awt.Color(204, 204, 255));
        tnSuaThongTinNhaHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tnSuaThongTinNhaHang.setForeground(new java.awt.Color(0, 0, 0));
        tnSuaThongTinNhaHang.setText("Sá»­a ThÃ´ng Tin NhÃ  HÃ ng");
        tnSuaThongTinNhaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnSuaThongTinNhaHangActionPerformed(evt);
            }
        });

        btnXemDanhSachNhaHang.setBackground(new java.awt.Color(204, 204, 255));
        btnXemDanhSachNhaHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXemDanhSachNhaHang.setForeground(new java.awt.Color(0, 0, 0));
        btnXemDanhSachNhaHang.setText("Xem danh sÃ¡ch nhÃ  hÃ ng");
        btnXemDanhSachNhaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemDanhSachNhaHangActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(204, 204, 204));
        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(0, 0, 0));
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(204, 204, 204));
        btnCapNhat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(0, 0, 0));
        btnCapNhat.setText("Cáº¬P NHáº¬T");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTimKiemNhaHang)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaThongTinNhaHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLuuThongTinNhaHang)
                        .addGap(18, 18, 18)
                        .addComponent(tnSuaThongTinNhaHang))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbLogoNhaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbDiaChi)
                                                    .addComponent(lbTenNhaHang)
                                                    .addComponent(lbMaNhaHang))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(txtMaNhaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbChiPhi)
                                            .addComponent(lbSoDienThoai)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbWebsite)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTenNhaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtChiPhi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(lbDanhMucNhaHang))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnXemDanhSachNhaHang)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCapNhat)
                .addGap(43, 43, 43)
                .addComponent(btnReset)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lbDanhMucNhaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMaNhaHang)
                            .addComponent(lbWebsite))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaNhaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTenNhaHang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNhaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDiaChi)
                            .addComponent(lbChiPhi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbLogoNhaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXemDanhSachNhaHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiemNhaHang)
                    .addComponent(btnXoaThongTinNhaHang)
                    .addComponent(btnLuuThongTinNhaHang)
                    .addComponent(tnSuaThongTinNhaHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnCapNhat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemDanhSachNhaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemDanhSachNhaHangActionPerformed
        // TODO add your handling code here:
        showNhaHang();      
    }//GEN-LAST:event_btnXemDanhSachNhaHangActionPerformed

    private void btnLuuThongTinNhaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuThongTinNhaHangActionPerformed
        // TODO add your handling code here:
        String maNH = txtMaNhaHang.getText();
        String tenNH = txtTenNhaHang.getText();
        String diachi = txtDiaChi.getText();
        String website = txtWebsite.getText();
        String soDT = txtSoDienThoai.getText();
        int chiphi = Integer.parseInt(txtChiPhi.getText());
        
        NhaHangDTO nhDTO = new NhaHangDTO(maNH, tenNH, diachi, website, soDT, chiphi);
        NhaHangBUS.luuTTNH(nhDTO);
        showNhaHang();
    }//GEN-LAST:event_btnLuuThongTinNhaHangActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtMaNhaHang.setText("");
        txtTenNhaHang.setText("");
        txtDiaChi.setText("");
        txtWebsite.setText("");
        txtWebsite.setText("");
        txtSoDienThoai.setText("");
        txtChiPhi.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTimKiemNhaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemNhaHangActionPerformed
        // TODO add your handling code here:
        Object[] options = {
            "TÃ¬m kiáº¿m theo mÃ£ nhÃ  hÃ ng", "TÃ¬m kiáº¿m theo tÃªn nhÃ  hÃ ng", "Ä�Ã³ng"
        };
        int select = JOptionPane.showOptionDialog(this, "Báº¡n muá»‘n tÃ¬m kiáº¿m theo phÆ°Æ¡ng thá»©c nÃ o?", "TÃ¹y chá»�n", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[2]);
        
        //System.out.println("select: " + select);
        //mÃ£ -> select: 0
        //tÃªn -> select: 1
        // chi phi -> select: 2
        // Ä‘Ã³ng -> select: 3
        
        if(select == 0){
            String input = JOptionPane.showInputDialog(this, "Má»�i báº¡n nháº­p mÃ£ nhÃ  hÃ ng !");
            
            if(input != null && input.length() > 0){
                nhahangList = NhaHangBUS.findByMaNH(input);
                tableModel.setRowCount(0);
                
                nhahangList.forEach(nhDTO -> {
                    tableModel.addRow(new Object[] {
                        nhDTO.getMaNH(), nhDTO.getTenNH(), nhDTO.getDiachi(), nhDTO.getWebsite(), nhDTO.getSoDT(), nhDTO.getChiphi()
                    });
                });
            }
            else {
                JOptionPane.showMessageDialog(null, "Lá»—i tÃ¬m kiáº¿m !");
            }
        }
        
        if(select == 1){
            String input = JOptionPane.showInputDialog(this, "Má»�i báº¡n nháº­p tÃªn nhÃ  hÃ ng");
            
            if(input != null && input.length() > 0){
                nhahangList = NhaHangBUS.findByTenNH(input);
                tableModel.setRowCount(0);
                
                nhahangList.forEach(nhDTO -> {
                    tableModel.addRow(new Object[]{
                        nhDTO.getMaNH(), nhDTO.getTenNH(), nhDTO.getDiachi(), nhDTO.getWebsite(), nhDTO.getSoDT(), nhDTO.getChiphi()
                    });
                });
            }
            else {
                JOptionPane.showMessageDialog(null, "Lá»—i tÃ¬m kiáº¿m !");
            }
        }
    }//GEN-LAST:event_btnTimKiemNhaHangActionPerformed

    private void btnXoaThongTinNhaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaThongTinNhaHangActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblNhaHang.getSelectedRow();
        if(selectedIndex >= 0){
            NhaHangDTO nhDTO = nhahangList.get(selectedIndex);
            
            int option = JOptionPane.showConfirmDialog(this, "Báº¡n cháº¯c cháº¯n muá»‘n xÃ³a thÃ´ng tin nÃ y ?");
            
            //System.out.println("option: " + option);
            //yes->0
            //No->1
            //Cancel->2
            
            if(option == 0){
                NhaHangBUS.XoaTTNH(nhDTO.getMaNH());
                showNhaHang();
            }
        }
    }//GEN-LAST:event_btnXoaThongTinNhaHangActionPerformed

    private void tnSuaThongTinNhaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnSuaThongTinNhaHangActionPerformed
        // TODO add your handling code here:
        showData();
    }//GEN-LAST:event_tnSuaThongTinNhaHangActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        String maNH = txtMaNhaHang.getText();
        String tenNH = txtTenNhaHang.getText();
        String diachi = txtDiaChi.getText();
        String website = txtWebsite.getText();
        String soDT = txtSoDienThoai.getText();
        int chiphi = Integer.parseInt(txtChiPhi.getText());
        
        NhaHangDTO nhDTO = new NhaHangDTO(maNH, tenNH, diachi, website, soDT, chiphi);
        NhaHangBUS.CapNhatTTNH(nhDTO);
        
        int i = tblNhaHang.getSelectedRow();
        NhaHangBUS.xemDSNH();
        tableModel.setValueAt(maNH, i, 0);
        tableModel.setValueAt(tenNH, i, 1);
        tableModel.setValueAt(diachi, i, 2);
        tableModel.setValueAt(website, i, 3);
        tableModel.setValueAt(soDT, i, 4);
        tableModel.setValueAt(chiphi, i, 5);
        tblNhaHang.setModel(tableModel);
    }//GEN-LAST:event_btnCapNhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhaHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhaHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhaHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhaHangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhaHangGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuuThongTinNhaHang;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTimKiemNhaHang;
    private javax.swing.JButton btnXemDanhSachNhaHang;
    private javax.swing.JButton btnXoaThongTinNhaHang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbChiPhi;
    private javax.swing.JLabel lbDanhMucNhaHang;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbLogoNhaHang;
    private javax.swing.JLabel lbMaNhaHang;
    private javax.swing.JLabel lbSoDienThoai;
    private javax.swing.JLabel lbTenNhaHang;
    private javax.swing.JLabel lbWebsite;
    private javax.swing.JTable tblNhaHang;
    private javax.swing.JButton tnSuaThongTinNhaHang;
    private javax.swing.JTextField txtChiPhi;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNhaHang;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenNhaHang;
    private javax.swing.JTextField txtWebsite;
    // End of variables declaration//GEN-END:variables
}
