package com.myclass.gui;

import com.myclass.bus.PhuongTienBUS;
import com.myclass.dto.PhuongTienDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Thin
 */
public class PhuongTienGUI extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    List<PhuongTienDTO> phuongtienList = new ArrayList<>();

    /**
     * Creates new form PhuongTien
     */
    public PhuongTienGUI() {
        initComponents();
        tableModel = (DefaultTableModel) tblPhuongTien.getModel();
    }

    private void showPhuongTien() {
        phuongtienList = PhuongTienBUS.XemDSPT();
        tableModel.setRowCount(0);
        phuongtienList.forEach(ptDTO -> {
            tableModel.addRow(new Object[]{
                ptDTO.getMaPT(), ptDTO.getTenPT(), ptDTO.getDiachi(), ptDTO.getSochongoi(), ptDTO.getSoDT(), ptDTO.getChiphi()
            });
        });
    }

    private void showData() {
        int selectedIndex = tblPhuongTien.getSelectedRow();

        if (selectedIndex >= 0) {
            PhuongTienDTO ptDTO = phuongtienList.get(selectedIndex);

            txtMaPT.setText(ptDTO.getMaPT());
            txtTenPT.setText(ptDTO.getTenPT());
            txtDiaChi.setText(ptDTO.getDiachi());
            txtSoChoNgoi.setText(Integer.toString(ptDTO.getSochongoi()));
            txtSoDienThoai.setText(ptDTO.getSoDT());
            txtChiPhi.setText(Integer.toString(ptDTO.getChiphi()));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbDanhMucNhaHang = new javax.swing.JLabel();
        lbLogoNhaHang = new javax.swing.JLabel();
        lbMaPT = new javax.swing.JLabel();
        txtMaPT = new javax.swing.JTextField();
        lbTenPT = new javax.swing.JLabel();
        txtTenPT = new javax.swing.JTextField();
        lbDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        lbChiPhi = new javax.swing.JLabel();
        txtChiPhi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhuongTien = new javax.swing.JTable();
        btnTimKiemPT = new javax.swing.JButton();
        btnXoaTTPT = new javax.swing.JButton();
        lbSoChoNgoi = new javax.swing.JLabel();
        txtSoChoNgoi = new javax.swing.JTextField();
        lbSoDienThoai = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        btnLuuTTPT = new javax.swing.JButton();
        btnSuaTTPT = new javax.swing.JButton();
        btnXemDSPT = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        lbDanhMucNhaHang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbDanhMucNhaHang.setForeground(new java.awt.Color(153, 0, 0));
        lbDanhMucNhaHang.setText("DANH Má»¤C PHÆ¯Æ NG TIá»†N");

        lbLogoNhaHang.setIcon(new javax.swing.ImageIcon("C:\\Users\\Thin\\OneDrive\\MÃ¡y tÃ­nh\\java\\QuanLyTourDuLich\\src\\main\\java\\IMAGE\\logoPhuongTien.PNG")); // NOI18N
        lbLogoNhaHang.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbMaPT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbMaPT.setForeground(new java.awt.Color(0, 0, 0));
        lbMaPT.setText("MÃ£ phÆ°Æ¡ng tiá»‡n");

        txtMaPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPTActionPerformed(evt);
            }
        });

        lbTenPT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbTenPT.setForeground(new java.awt.Color(0, 0, 0));
        lbTenPT.setText("TÃªn phÆ°Æ¡ng tiá»‡n");

        lbDiaChi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbDiaChi.setForeground(new java.awt.Color(0, 0, 0));
        lbDiaChi.setText("Ä�á»‹a chá»‰ thuÃª");

        lbChiPhi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbChiPhi.setForeground(new java.awt.Color(0, 0, 0));
        lbChiPhi.setText("Chi phÃ­ / NgÆ°á»�i");

        tblPhuongTien.setBackground(new java.awt.Color(204, 204, 255));
        tblPhuongTien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        tblPhuongTien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tblPhuongTien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ£ phÆ°Æ¡ng tiá»‡n", "TÃªn phÆ°Æ¡ng tiá»‡n", "Ä�á»‹a chá»‰ thuÃª", "Sá»‘ chá»— ngá»“i", "Sá»‘ Ä‘iá»‡n thoáº¡i", "Chi phÃ­/ NgÆ°á»�i"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPhuongTien);

        btnTimKiemPT.setBackground(new java.awt.Color(204, 204, 255));
        btnTimKiemPT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTimKiemPT.setForeground(new java.awt.Color(0, 0, 0));
        btnTimKiemPT.setText("TÃ¬m Kiáº¿m PhÆ°Æ¡ng Tiá»‡n");
        btnTimKiemPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemPTActionPerformed(evt);
            }
        });

        btnXoaTTPT.setBackground(new java.awt.Color(204, 204, 255));
        btnXoaTTPT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoaTTPT.setForeground(new java.awt.Color(0, 0, 0));
        btnXoaTTPT.setText("XÃ³a ThÃ´ng Tin PhÆ°Æ¡ng Tiá»‡n");
        btnXoaTTPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTTPTActionPerformed(evt);
            }
        });

        lbSoChoNgoi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbSoChoNgoi.setForeground(new java.awt.Color(0, 0, 0));
        lbSoChoNgoi.setText("Sá»‘ chá»— ngá»“i");

        lbSoDienThoai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbSoDienThoai.setForeground(new java.awt.Color(0, 0, 0));
        lbSoDienThoai.setText("Sá»‘ Ä‘iá»‡n thoáº¡i");

        btnLuuTTPT.setBackground(new java.awt.Color(204, 204, 255));
        btnLuuTTPT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLuuTTPT.setForeground(new java.awt.Color(0, 0, 0));
        btnLuuTTPT.setText("LÆ°u ThÃ´ng Tin PhÆ°Æ¡ng Tiá»‡n");
        btnLuuTTPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuTTPTActionPerformed(evt);
            }
        });

        btnSuaTTPT.setBackground(new java.awt.Color(204, 204, 255));
        btnSuaTTPT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSuaTTPT.setForeground(new java.awt.Color(0, 0, 0));
        btnSuaTTPT.setText("Sá»­a ThÃ´ng Tin PhÆ°Æ¡ng Tiá»‡n");
        btnSuaTTPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTTPTActionPerformed(evt);
            }
        });

        btnXemDSPT.setBackground(new java.awt.Color(204, 204, 255));
        btnXemDSPT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXemDSPT.setForeground(new java.awt.Color(0, 0, 0));
        btnXemDSPT.setText("Xem Danh SÃ¡ch PhÆ°Æ¡ng Tiá»‡n");
        btnXemDSPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemDSPTActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(204, 204, 204));
        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(0, 0, 0));
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(204, 204, 204));
        btnCapNhat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(0, 0, 0));
        btnCapNhat.setText("Cáº¬P NHáº¬T");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnXemDSPT)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbDiaChi)
                                            .addComponent(lbTenPT)
                                            .addComponent(lbMaPT))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtMaPT, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbChiPhi)
                                    .addComponent(lbSoDienThoai)
                                    .addComponent(lbSoChoNgoi)
                                    .addComponent(txtSoChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenPT, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbLogoNhaHang)
                        .addGap(176, 176, 176)
                        .addComponent(lbDanhMucNhaHang)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTimKiemPT)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaTTPT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLuuTTPT)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaTTPT))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbDanhMucNhaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMaPT)
                            .addComponent(lbSoChoNgoi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSoDienThoai, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTenPT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbLogoNhaHang)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiaChi)
                    .addComponent(lbChiPhi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXemDSPT))
                    .addComponent(txtChiPhi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTimKiemPT)
                        .addComponent(btnXoaTTPT))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuuTTPT)
                            .addComponent(btnSuaTTPT))
                        .addGap(12, 12, 12)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnCapNhat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemPTActionPerformed

        Object[] options = {
            "TÃ¬m kiÃªm theo mÃ£ phÆ°Æ¡ng tiá»‡n", "TÃ¬m kiáº¿m theo tÃªn phÆ°Æ¡ng tiá»‡n", "Ä�Ã³ng"
        };
        int select = JOptionPane.showOptionDialog(this, "Báº¡n muá»‘n tÃ¬m kiáº¿m theo phÆ°Æ¡ng thá»©c nÃ o ?", "TÃ¹y chá»�n", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[2]);
        //System.out.println("select: " + select);
        //mÃ£ -> select: 0
        //tÃªn -> select: 1
        // chi phi -> select: 2
        // Ä‘Ã³ng -> select: 3

        if (select == 0) {
            String input = JOptionPane.showInputDialog(this, "Má»�i báº¡n nháº­p mÃ£ phÆ°Æ¡ng tiá»‡n !");

            if (input != null && input.length() > 0) {
                phuongtienList = PhuongTienBUS.findByMaPT(input);
                tableModel.setRowCount(0);

                phuongtienList.forEach(ptDTO -> {
                    tableModel.addRow(new Object[]{
                        ptDTO.getMaPT(), ptDTO.getTenPT(), ptDTO.getDiachi(), ptDTO.getSochongoi(), ptDTO.getSoDT(), ptDTO.getChiphi()
                    });
                });
            } else {
                JOptionPane.showMessageDialog(null, "Lá»—i tÃ¬m kiáº¿m !");
            }
        }

        if (select == 1) {
            String input = JOptionPane.showInputDialog(this, "Má»�i báº¡n nháº­p tÃªn nhÃ  hÃ ng");

            if (input != null && input.length() > 0) {
                phuongtienList = PhuongTienBUS.findByTenPT(input);
                tableModel.setRowCount(0);

                phuongtienList.forEach(ptDTO -> {
                    tableModel.addRow(new Object[]{
                        ptDTO.getMaPT(), ptDTO.getTenPT(), ptDTO.getDiachi(), ptDTO.getSochongoi(), ptDTO.getSoDT(), ptDTO.getChiphi()
                    });
                });
            } else {
                JOptionPane.showMessageDialog(null, "Lá»—i tÃ¬m kiáº¿m !");
            }
        }
    }//GEN-LAST:event_btnTimKiemPTActionPerformed

    private void btnXoaTTPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTTPTActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tblPhuongTien.getSelectedRow();
        if(selectedIndex >= 0){
            PhuongTienDTO ptDTO = phuongtienList.get(selectedIndex);
            
            int option = JOptionPane.showConfirmDialog(this, "Báº¡n cháº¯c cháº¯n muá»‘n xÃ³a thÃ´ng tin nÃ y ?");
            //System.out.println("option: " + option);
            //yes->0
            //No->1
            //Cancel->2
            
            if(option == 0){
                PhuongTienBUS.xoaDSPT(ptDTO.getMaPT());
                showPhuongTien();
            }
        }
    }//GEN-LAST:event_btnXoaTTPTActionPerformed

    private void btnLuuTTPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuTTPTActionPerformed
        // TODO add your handling code here:
        String maPT = txtMaPT.getText();
        String tenPT = txtTenPT.getText();
        String diachi = txtDiaChi.getText();
        int sochongoi = Integer.parseInt(txtSoChoNgoi.getText());
        String soDT = txtSoDienThoai.getText();
        int chiphi =Integer.parseInt(txtChiPhi.getText());
        
        PhuongTienDTO ptDTO = new PhuongTienDTO(maPT, tenPT, diachi, sochongoi, soDT, chiphi);
        
        PhuongTienBUS.luuDSPT(ptDTO);
        showPhuongTien();
    }//GEN-LAST:event_btnLuuTTPTActionPerformed

    private void btnSuaTTPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTTPTActionPerformed
        // TODO add your handling code here:
        showData();

    }//GEN-LAST:event_btnSuaTTPTActionPerformed

    private void btnXemDSPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemDSPTActionPerformed
        // TODO add your handling code here:
        showPhuongTien();
    }//GEN-LAST:event_btnXemDSPTActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtMaPT.setText("");
        txtTenPT.setText("");
        txtDiaChi.setText("");
        txtSoChoNgoi.setText("");
        txtSoDienThoai.setText("");
        txtChiPhi.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
         String maPT = txtMaPT.getText();
        String tenPT = txtTenPT.getText();
        String diachi = txtDiaChi.getText();
        String sochongoi = txtSoChoNgoi.getText();
        String soDT = txtSoDienThoai.getText();
        int chiphi = Integer.parseInt(txtChiPhi.getText());
        
        PhuongTienDTO ptDTO = new PhuongTienDTO(maPT, tenPT, diachi, chiphi, soDT, chiphi);
        PhuongTienBUS.CapNhatTTPT(ptDTO);
        
        int i = tblPhuongTien.getSelectedRow();
        PhuongTienBUS.XemDSPT();
        tableModel.setValueAt(maPT, i, 0);
        tableModel.setValueAt(tenPT, i, 1);
        tableModel.setValueAt(diachi, i, 2);
        tableModel.setValueAt(sochongoi, i, 3);
        tableModel.setValueAt(soDT, i, 4);
        tableModel.setValueAt(chiphi, i, 5);
        tblPhuongTien.setModel(tableModel);

    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtMaPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhuongTienGUI

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhuongTienGUI

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhuongTienGUI

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhuongTienGUI

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhuongTienGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLuuTTPT;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSuaTTPT;
    private javax.swing.JButton btnTimKiemPT;
    private javax.swing.JButton btnXemDSPT;
    private javax.swing.JButton btnXoaTTPT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbChiPhi;
    private javax.swing.JLabel lbDanhMucNhaHang;
    private javax.swing.JLabel lbDiaChi;
    private javax.swing.JLabel lbLogoNhaHang;
    private javax.swing.JLabel lbMaPT;
    private javax.swing.JLabel lbSoChoNgoi;
    private javax.swing.JLabel lbSoDienThoai;
    private javax.swing.JLabel lbTenPT;
    private javax.swing.JTable tblPhuongTien;
    private javax.swing.JTextField txtChiPhi;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaPT;
    private javax.swing.JTextField txtSoChoNgoi;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenPT;
    // End of variables declaration//GEN-END:variables
}
